// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBwVNODEbLfsSNaciOodWm-gRyh9TrdkY',
    appId: '1:765416554245:web:30779382b0b03e155ac16c',
    messagingSenderId: '765416554245',
    projectId: 'gamer-rage',
    authDomain: 'gamer-rage.firebaseapp.com',
    storageBucket: 'gamer-rage.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIS8n1s2peA89s9BaIMZamLwDGwu_f1KI',
    appId: '1:765416554245:android:6199cbe4d9ef344f5ac16c',
    messagingSenderId: '765416554245',
    projectId: 'gamer-rage',
    storageBucket: 'gamer-rage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCktPYWADfc4je_NFwBg8gWL8q5f-9GT7c',
    appId: '1:765416554245:ios:e2d15cfee4bb28705ac16c',
    messagingSenderId: '765416554245',
    projectId: 'gamer-rage',
    storageBucket: 'gamer-rage.firebasestorage.app',
    iosBundleId: 'com.example.gamerRage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBwVNODEbLfsSNaciOodWm-gRyh9TrdkY',
    appId: '1:765416554245:web:64930aa2634e90975ac16c',
    messagingSenderId: '765416554245',
    projectId: 'gamer-rage',
    authDomain: 'gamer-rage.firebaseapp.com',
    storageBucket: 'gamer-rage.firebasestorage.app',
  );
}
